export const siteConfig = {
  brand: {
    name: "Kavrix Labs",
    shortName: "Kavrix",
    heroTitle: "Digital work that feels",
    heroAccent: "alive.",
    heroDescription:
      "Creative production, front-end experiences, and digital support for brands that want sharper execution without adding another layer of chaos.",
    eyebrow: "Creative studio · Digital partner",
  },
  contact: {
    email: "hello@kavrixlabs.com",
    // Replace these generic platform destinations with your real profiles when available.
    phone: "",
    whatsappNumber: "",
    whatsappMessage: "Hi Kavrix Labs, I would like to discuss a project.",
    socials: {
      instagram: "https://www.instagram.com/",
      linkedin: "https://www.linkedin.com/",
      facebook: "https://www.facebook.com/",
      youtube: "https://www.youtube.com/",
      twitter: "https://x.com/",
    },
  },
  heroMedia: {
    main: {
      image: "https://images.unsplash.com/photo-1768222935380-0a3a76fbb42e?auto=format&fit=crop&fm=jpg&q=84&w=1800",
      imageAlt: "Professional video production control room with multiple screens",
    },
    secondary: {
      image: "https://images.unsplash.com/photo-1763568258187-a0d90864ed66?auto=format&fit=crop&fm=jpg&q=84&w=1200",
      imageAlt: "Laptop displaying code in a dark development workspace",
    },
  },
  services: [
    {
      title: "Video Editing",
      description: "Fast, polished edits built around retention, rhythm, story, and platform-specific delivery.",
      visual: "VIDEO",
      className: "violet",
      subcategories: ["YouTube Editing", "Short-form & Reels", "Podcast Editing", "Product Videos", "Color & Audio Polish", "Captions & Repurposing"],
    },
    {
      title: "Motion Graphics",
      description: "Motion systems, animated identities, explainers, titles, and visual effects that add energy without adding noise.",
      visual: "MOTION",
      className: "cyan",
      subcategories: ["2D Motion", "3D Motion", "Logo Animation", "Kinetic Type", "Explainers", "VFX & Titles"],
    },
    {
      title: "Graphic Designing",
      description: "Brand-ready visual systems for campaigns, social, presentations, print, and digital communication.",
      visual: "DESIGN",
      className: "orange",
      subcategories: ["Brand Identity", "Social Creatives", "Thumbnails", "Pitch Decks", "Packaging", "Campaign Design"],
    },
    {
      title: "UI/UX Design",
      description: "Clear interface design shaped around hierarchy, interaction, usability, and responsive behavior.",
      visual: "UI/UX",
      className: "lime",
      subcategories: ["Web UI", "Mobile UI", "Dashboards", "Wireframes", "Prototypes", "Design Systems"],
    },
    {
      title: "Social Media Management",
      description: "Content planning and day-to-day social execution that keeps your brand consistent and active.",
      visual: "SOCIAL",
      className: "pink",
      subcategories: ["Content Planning", "Publishing", "Captions", "Community", "Analytics", "Platform Management"],
    },
    {
      title: "Web Development",
      description: "Responsive websites and landing pages with a strong visual layer, clean interactions, and practical performance.",
      visual: "CODE",
      className: "blue",
      subcategories: ["React Websites", "Landing Pages", "Responsive UI", "E-commerce UI", "Redesigns", "Performance Polish"],
    },
    {
      title: "Email Marketing",
      description: "Campaign design, newsletters, automations, and lifecycle communication that feels intentional rather than spammy.",
      visual: "EMAIL",
      className: "gold",
      subcategories: ["Campaigns", "Newsletters", "Templates", "Automation", "Segmentation", "Reporting"],
    },
    {
      title: "Lead Generation",
      description: "Structured prospect research and list building for teams that need useful opportunities, not random spreadsheets.",
      visual: "LEADS",
      className: "teal",
      subcategories: ["B2B Research", "B2C Research", "LinkedIn Leads", "Email Leads", "Verification", "CRM Support"],
    },
    {
      title: "Virtual Assistant",
      description: "Flexible operational support for the repetitive work that still needs to be done properly.",
      visual: "VA",
      className: "indigo",
      subcategories: ["Admin Support", "Research", "Email", "Calendar", "CRM", "Data & Documents"],
    },
    {
      title: "E-commerce",
      description: "Store support across product content, catalog operations, customer workflows, and front-end presentation.",
      visual: "SHOP",
      className: "emerald",
      subcategories: ["Shopify Support", "Product Listings", "Catalog Cleanup", "Store Content", "Customer Support", "Optimization"],
    },
  ],
  portfolio: [
    {
      title: "Comfrt",
      category: "Apparel & DTC",
      type: "Live Production Flagship",
      liveUrl: "https://comfrt.com",
      description:
        "Feel-good weighted hoodies, plush blankets, and anxiety-relief loungewear engineered on Shopify Plus with headless Bento & Outsmartly acceleration for sub-second page loads.",
      image: "https://cdn.shopify.com/s/files/1/0569/4029/8284/files/WEB_LINK_1.jpg?v=1783966011",
      imageAlt: "Comfrt apparel and feel-good weighted clothing flagship store",
      credit: "comfrt.com · Live Store",
      creditUrl: "https://comfrt.com",
      tags: ["Shopify Plus", "Headless Bento", "Custom PDP Swatches", "Rebuy Upsells"],
      metrics: ["Shopify Plus Flagship", "Sub-second Speeds", "Dynamic Swatch Matrix"],
      accentColor: "#f4efe6",
      review: {
        clientGoal: "Scale a high-growth DTC apparel brand specializing in slightly weighted hoodies and anxiety-reducing loungewear, handling viral flash-sale traffic with zero downtime.",
        techStack: ["Shopify Plus", "Bento Headless State Layer", "Outsmartly CDN Edge", "Custom Liquid", "Rebuy Engine", "Klaviyo", "Elevar Analytics"],
        featuresEngineered: [
          "Custom PDP with instant color & size variant swatch synchronization",
          "Headless Outsmartly edge delivery layer for instant page loads",
          "Dynamic slide-out cart drawer with intelligent Rebuy cross-sells",
          "Integrated Comfrt Club loyalty gating and VIP checkout routing",
        ],
        performanceImpact: "Maintained ultra-fast under-1s page load times during peak traffic surges, boosting mobile conversion rate significantly across international markets.",
        scorecard: { mobileUx: "99%", architecture: "Headless / Edge Hybrid", coreWebVitals: "Grade A" },
      },
    },
    {
      title: "PurelyWHITE DELUXE™",
      category: "Oral Care & Beauty",
      type: "Live Production Flagship",
      liveUrl: "https://purelywhitedeluxe.com",
      description:
        "Award-winning dentist-formulated teeth whitening brand serving over 1 million customers, featuring custom bundle builders, video testimonials, and high-converting checkouts.",
      image: "https://purelywhitedeluxe.com/cdn/shop/files/Untitled_design_1.png?v=1691467284",
      imageAlt: "PurelyWHITE DELUXE award-winning teeth whitening oral care store",
      credit: "purelywhitedeluxe.com · Live Store",
      creditUrl: "https://purelywhitedeluxe.com",
      tags: ["DTC Oral Care", "Bundle Builder", "TriplePixel", "Afterpay / Shop Pay"],
      metrics: ["1M+ Happy Customers", "4.9/5 Rating", "High-Converting Checkout Funnel"],
      accentColor: "#334ead",
      review: {
        clientGoal: "Create a high-converting DTC health and beauty sales funnel that highlights clinical dentist formulation, social proof, and seamless multi-item bundles.",
        techStack: ["Shopify", "Custom Liquid", "Island Architecture (is-land)", "Parallax Video Modules", "TriplePixel Analytics", "Afterpay", "Shop Pay"],
        featuresEngineered: [
          "Interactive bundle builder with multi-tier volume discounts",
          "Video testimonial carousel with high-converting mobile modal player",
          "Optimized one-click checkout integration with Afterpay and Shop Pay",
          "Real-time stock reservation and urgency indicators",
        ],
        performanceImpact: "Maximized mobile checkout velocity, resulting in sustained multi-million dollar annual sales with exceptional customer retention.",
        scorecard: { mobileUx: "98%", architecture: "Modular Island Architecture", coreWebVitals: "Ultra Fast" },
      },
    },
    {
      title: "Atelier RMR Montreal",
      category: "Luxury Fine Jewellery",
      type: "Live Production Flagship",
      liveUrl: "https://atelierrmr.com/",
      description:
        "Montreal's artisanal custom jewellery workshop since 1978, featuring a bespoke bilingual (EN/FR) experience, custom ring showcase, Swiper galleries, and CAD/USD checkout.",
      image: "https://atelierrmr.com/cdn/shop/files/Atelier_RMR_Montreal.jpg?v=1699632346",
      imageAlt: "Atelier RMR Montreal artisanal custom fine jewellery digital flagship",
      credit: "atelierrmr.com · Live Store",
      creditUrl: "https://atelierrmr.com/",
      tags: ["Luxury Jewellery", "Bilingual EN/FR", "Swiper Galleries", "Multi-Currency CAD/USD"],
      metrics: ["Est. 1978 in Montreal", "Bespoke Ring Inquiry Flow", "Full Multilingual Architecture"],
      accentColor: "#d4af37",
      review: {
        clientGoal: "Digitize an esteemed Montreal luxury fine jewellery atelier into a prestigious digital flagship reflecting handcrafted heritage, bespoke ring requests, and international clientele.",
        techStack: ["Shopify", "Be Yours Custom Architecture", "Swiper.js Engine", "Shopify Multi-Currency (CAD/USD)", "iSense GDPR/CCPA Suite", "Bilingual Sub-Routing"],
        featuresEngineered: [
          "Seamless English and French bilingual localization with automated URL routing",
          "Bespoke diamond & custom engagement ring consultation request flow",
          "Touch-optimized Swiper.js image galleries with macro zoom",
          "Integrated Shop Pay and Apple Pay 3DS compliance for luxury transactions",
        ],
        performanceImpact: "Elevated high-ticket average order value ($2,000+ AOV) with a prestige aesthetic that matches Montreal's premier fine jewellery workshop.",
        scorecard: { mobileUx: "97%", architecture: "Luxury Bespoke Shopify", coreWebVitals: "Smooth 60fps" },
      },
    },
    {
      title: "SEVEN:THIRTY SKINCARE",
      category: "Clean Skincare",
      type: "Live Production Flagship",
      liveUrl: "https://seventhirty.co",
      description:
        "Professional facial products and intentionally formulated skincare solutions with modern View Transitions, ingredient breakdown drawers, and sleek mobile UX.",
      image: "https://seventhirty.co/cdn/shop/files/730-thumbnail.jpg?v=1677616405",
      imageAlt: "SEVEN:THIRTY SKINCARE professional facial products and clean beauty storefront",
      credit: "seventhirty.co · Live Store",
      creditUrl: "https://seventhirty.co",
      tags: ["Clean Beauty", "View Transitions API", "Ingredient Transparency", "Mobile-First"],
      metrics: ["Native View Transitions", "Clean Editorial Aesthetic", "Zero Layout Shift"],
      accentColor: "#c6a882",
      review: {
        clientGoal: "Design and engineer an editorial, minimalist storefront for clinical-grade skincare solutions that builds immense trust through ingredient transparency and smooth transitions.",
        techStack: ["Shopify", "Modern View Transitions API", "Custom CSS Architecture", "Google Analytics 4", "Klaviyo Lifecycle Automations"],
        featuresEngineered: [
          "Native Same-Origin View Transitions for app-like smooth page navigation",
          "Interactive ingredient deep-dive drawers on product detail pages",
          "Skin type routine recommendation selector",
          "Sleek floating navigation with frictionless slide-out cart",
        ],
        performanceImpact: "Achieved high mobile dwell times and repeat purchase rates thanks to an effortless, editorial shopping journey.",
        scorecard: { mobileUx: "99%", architecture: "View Transitions / Modern Web", coreWebVitals: "Grade A+" },
      },
    },
    {
      title: "FAJ Trading L.L.C",
      category: "Commercial Equipment & B2B",
      type: "Live Production Flagship",
      liveUrl: "https://fajtradingllc.com",
      description:
        "Large-scale commercial marketplace and equipment supplier in Dubai, UAE & MENA for coffee machines, electronics, refrigeration, ACs, and electrical analyzers.",
      image: "https://www.fajtradingllc.com/cdn/shop/files/Faj_Trading_llc_Logo_1000_x_500.png?v=1766221725",
      imageAlt: "FAJ Trading L.L.C Dubai commercial equipment and coffee machines supplier",
      credit: "fajtradingllc.com · Live Store",
      creditUrl: "https://fajtradingllc.com",
      tags: ["B2B / B2C Commerce", "Dubai & MENA Region", "Mega-Menu Catalog", "Equipment Wholesale"],
      metrics: ["10,000+ SKUs", "Multi-Region Shipping", "B2B Request For Quote"],
      accentColor: "#c8112e",
      review: {
        clientGoal: "Build a robust B2B and B2C commercial equipment portal capable of handling extensive product catalogs, spare parts lookup, regional logistics across UAE/MENA, and commercial procurement.",
        techStack: ["Shopify Enterprise Theme", "Custom Mega-Menu Engine", "Dynamic Currency & Logistics Router", "High-Volume Catalog Indexer"],
        featuresEngineered: [
          "Multi-tier mega navigation categorizing thousands of commercial parts and machinery",
          "Regional shipping and delivery calculation across UAE, Saudi Arabia, Oman, and Egypt",
          "Quick quote (RFQ) procurement for corporate hospitality and industrial clients",
          "Fast search with instant category and brand filtering",
        ],
        performanceImpact: "Enabled scalable multi-channel sales across the Middle East with lightning-fast catalog search across heavy inventory.",
        scorecard: { mobileUx: "96%", architecture: "Enterprise Catalog Engine", coreWebVitals: "High Throughput" },
      },
    },
    {
      title: "Kawaii Slime Company",
      category: "Toys & Sensory Play",
      type: "Live Production Flagship",
      liveUrl: "https://www.kawaiislimecompany.com/",
      description:
        "Viral sensory toys, custom DIY slime supplies, and creative kits engineered with interactive free gift unlock gates, pastel branding, and subscription bundles.",
      image: "https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?auto=format&fit=crop&fm=jpg&q=82&w=1600",
      imageAlt: "Kawaii Slime Company sensory toys and creative DIY slime products",
      credit: "kawaiislimecompany.com · Live Store",
      creditUrl: "https://www.kawaiislimecompany.com/",
      tags: ["Gamified E-Commerce", "Free Gift Gate JS", "Sensory Swatches", "Quicksand/Nunito UI"],
      metrics: ["Viral Social Sensation", "Gamified Tier Unlocks", "Custom Cart Rewards"],
      accentColor: "#FFA8BD",
      review: {
        clientGoal: "Deliver an unforgettable, joyful, and gamified shopping experience for a viral sensory slime and DIY toy brand beloved by kids and collectors worldwide.",
        techStack: ["Shopify", "Custom Free Gift Gate JS Engine", "Quicksand & Nunito Variable Fonts", "Interactive Cart Drawer", "Subscription App Hooks"],
        featuresEngineered: [
          "Custom free-gift tier gate logic (free squishy, full-size slime, plush unlocks based on cart value)",
          "Tactile texture and scent swatch selector for DIY slimes",
          "Playful pastel UI components (#FFA8BD) with bouncy interactive feedback",
          "Streamlined mobile checkout built for parent and youth shoppers",
        ],
        performanceImpact: "Drastically increased Average Order Value (AOV) by incentivizing cart tier thresholds through the custom gift unlock engine.",
        scorecard: { mobileUx: "98%", architecture: "Gamified Commerce Engine", coreWebVitals: "Optimized" },
      },
    },
    {
      title: "Directory Mockups",
      category: "Digital Products & Tools",
      type: "Live Production Flagship",
      liveUrl: "https://mockups.directory/",
      description:
        "Curated high-quality PSD mockups of digital devices, stationery, and packaging with instant digital delivery and automated EU/UK VAT compliance via Sufio.",
      image: "https://mockups.directory/cdn/shop/files/DirectorySocial.jpg?v=1676207078",
      imageAlt: "Directory Mockups premium digital PSD resources and device mockups",
      credit: "mockups.directory · Live Store",
      creditUrl: "https://mockups.directory/",
      tags: ["Digital Downloads", "Sufio VAT Automation", "High-Resolution PSDs", "Minimalist Grid"],
      metrics: ["Automated Global VAT", "Instant Download Fulfillment", "Designer-Grade PSDs"],
      accentColor: "#ffffff",
      review: {
        clientGoal: "Create a high-end, brutalist digital goods marketplace for world-class designers and agencies needing realistic device, stationery, and branding mockups.",
        techStack: ["Shopify", "Sufio Automated Tax/VAT Compliance Engine", "Digital Downloads Webhooks", "High-Resolution Image Zoom Grid"],
        featuresEngineered: [
          "Automated B2B customer VAT validation and zero-rating for EU and UK clients via Sufio",
          "Instant digital file fulfillment immediately post-checkout",
          "Minimalist high-contrast grid with seamless device filter categorization",
          "Responsive preview lightbox with detailed PSD technical specifications",
        ],
        performanceImpact: "Zero manual fulfillment overhead with 100% automated cross-border tax compliance, empowering international studio sales.",
        scorecard: { mobileUx: "99%", architecture: "Automated Digital Pipeline", coreWebVitals: "Instant" },
      },
    },
  ],
  labels: {
    primaryCta: "Start a project",
    secondaryCta: "Explore the work",
    portfolioTitle: "Selected Client Stores & Digital Flagships.",
    portfolioSubtitle: "Real production stores engineered for high-volume DTC brands, bespoke luxury jewelers, international B2B distributors, and digital resource creators.",
    contactTitle: "Bring us the complicated bit.",
    contactSubtitle: "Start with an email. The rest can be sorted out like civilized people after that.",
    footerText: "Creative production · Digital design · Front-end experiences",
  },
  theme: {
    accent: "#b8ff3d",
    accent2: "#7c5cff",
    background: "#08090d",
    surface: "#11131a",
    text: "#f5f7fb",
    muted: "#9ba3b2",
  },
} as const;
